import { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import Link from 'next/link'

import { supabase } from '../utils/supabase'
import { useUser } from '../context/user'

export default function Home({ lessons }: InferGetStaticPropsType<typeof getStaticProps>) {

  return (
    <>
      <Head>
        <title>Supbase SaaS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='my-16 max-w-3xl mx-auto'>
        {
          lessons?.map(lesson => (
            <Link key={lesson.id} href={`/${lesson.id}`} className='mb-4 rounded shadow p-8 h-20 flex'>
              {lesson.title}
            </Link>
          ))
        }
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const { data: lessons } = await supabase.from('lesson').select('*')
  return {
    props: {
      lessons
    }
  }
}
